{
 "title": "Parachain Rococo Candidates",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Candidate Duration per Stage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_1_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 1"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_2_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 2"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_3_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 3"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_4_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 4"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_5_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_6_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 6"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_7_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 7"
    }
   ]
  },
  {
   "title": "Total Candidates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "parachain_total_candidates", "legendFormat": "Total Parachain Candidates" }
   ]
  },
  {
   "title": "Candidates in Each Stage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " stage_1_candidates", "legendFormat": "Candidate Selection" },
    { "expr": "stage_2_candidates", "legendFormat": "Candidate Backing" },
    { "expr": "stage_3_candidates", "legendFormat": "StatementDistribution" },
    { "expr": "stage_4_candidates", "legendFormat": "PoVDistribution" },
    { "expr": "stage_5_candidates", "legendFormat": "AvailabilityDistribution" },
    { "expr": "stage_6_candidates", "legendFormat": "AvailabilityRecovery" },
    { "expr": "stage_7_candidates", "legendFormat": "BitfieldDistribution" },
    {}
   ]
  }
 ]
}