{
 "title": "Parachain Rococo Candidates",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Candidate Duration per Stage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_0_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 0 (no stage)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_1_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 1"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_2_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 2"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_3_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 3"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_4_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 4"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_5_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_6_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 6"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_7_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 7"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dotjaeger_stage_8_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 8"
    }
   ]
  },
  {
   "title": "Candidates in Each Stage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " dotjaeger_stage_1_candidates", "legendFormat": "Candidate Selection" },
    { "expr": "dotjaeger_stage_2_candidates", "legendFormat": "Candidate Backing" },
    {
     "expr": "dotjaeger_dotjaeger_stage_3_candidates",
     "legendFormat": "StatementDistribution"
    },
    { "expr": "dotjaeger_stage_4_candidates", "legendFormat": "PoVDistribution" },
    { "expr": "dotjaeger_stage_5_candidates", "legendFormat": "AvailabilityDistribution" },
    { "expr": "dotjaeger_stage_6_candidates", "legendFormat": "AvailabilityRecovery" },
    { "expr": "dotjaeger_stage_7_candidates", "legendFormat": "BitfieldDistribution" },
    { "expr": "dotjaeger_stage_8_candidates", "legendFormat": "ApprovalChecking" }
   ]
  },
  {
   "title": "Total Candidates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotjaeger_parachain_total_candidates",
     "legendFormat": "Total Parachain Candidates"
    }
   ]
  },
  {
   "title": "Stage 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_1_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 1"
    }
   ]
  },
  {
   "title": "Stage 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_2_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 2"
    }
   ]
  },
  {
   "title": "Stage 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_3_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 3"
    }
   ]
  },
  {
   "title": "Stage 4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_4_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 4"
    }
   ]
  },
  {
   "title": "Stage 5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_5_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 5"
    }
   ]
  },
  {
   "title": "Stage 6",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_6_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 6"
    }
   ]
  },
  {
   "title": "Stage 7",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stage_7_duration_bucket[5m])) by (le))",
     "legendFormat": "Stage 7"
    }
   ]
  }
 ]
}